# Generated by Django 3.2.12 on 2022-03-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('assignments', '0003_alter_assignments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_course', to='courses.courses'),
            preserve_default=False,
        ),
    ]
